# Generated by Django 2.1 on 2018-10-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badparking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingremalparqueado',
            old_name='latitud',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='ingremalparqueado',
            name='longitud',
        ),
    ]
