# Generated by Django 2.1 on 2018-10-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badparking', '0003_auto_20181029_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
